url: https://122e4e-mapbox.global.ssl.fastly.net
api: https://122e4e-mapbox.global.ssl.fastly.net/core
tileApi: https://api-maps-staging.tilestream.net
permalink: /:categories/:title/
baseurl: /mapping
title: Mapping with OpenStreetMap
markdown: kramdown
exclude:
- package.json
- node_modules

kramdown:
  auto_ids: true
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo

defaults:
- scope:
    path: "" # an empty string here means all files in the project
    type: "post" # previously `post` in Jekyll 2.2.
  values:
    layout: "post"
# DEFAULT ENGLISH
- scope:
    path: ""
    type: "page"
  values:
    lang: "en"
- scope:
    path: ""
    type: "post"
  values:
    lang: "en"
# SPANISH
- scope:
    path: "es"
    type: "page"
  values:
    lang: "es"
- scope:
    path: "es"
    type: "post"
  values:
    lang: "es"